### ISSUE TITLE
devkit release native-android don't build

### ISSUE THREAD

**Issue by jgamao** [gameclosure/devkit2-issues-view-only#108] opened 2015-02-11 09:47 UTC
[jvmtools]    connected to localhost:52381
[build-browser]    Finished packaging resources
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-world-map-20.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-world-map-21.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-world-map-22.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-inventory0.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-inventory1.png
 [build-native]    Writing resource: spritesheets/resources-images-characterScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-characterScreen1.png
 [build-native]    Writing resource: spritesheets/resources-images-countryScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-countryScreen1.png
 [build-native]    Writing resource: spritesheets/resources-images-countryScreen2.png
 [build-native]    Writing resource: spritesheets/resources-images-statsScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-itemdrops_uncomplete0.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets0.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets1.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets2.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets3.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets4.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen1.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen2.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen3.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen4.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen5.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen6.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-backup0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-item_dock0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-items0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-naruto0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-stickman0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-archive-naruto0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-archive-stickman0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-base0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity1.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity2.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity3.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity4.png
 [build-native]    Writing resource: spritesheets/resources-images-topScoreScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-ui0.png
 [build-native]    Writing resource: spritesheets/resources-images-titleScreen0.png
 [build-native]    Writing resource: resources/images/shopScreen.zip
 [build-native]    Writing resource: resources/audio/music/gameScreen.mp3
 [build-native]    Writing resource: resources/audio/music/titleScreen.mp3
 [build-native]    Writing resource: resources/audio/sounds/jump.mp3
 [build-native]    writing files to /home/joselito/wt-calamityrun/build/debug/native-android/assets/resources
wrote spritesheets/resources-images-pregameScreen0.png
wrote spritesheets/resources-images-pregameScreen-world-map-20.png
wrote spritesheets/resources-images-pregameScreen-world-map-21.png
wrote spritesheets/resources-images-pregameScreen-world-map-22.png
wrote spritesheets/resources-images-pregameScreen-inventory0.png
wrote spritesheets/resources-images-pregameScreen-inventory1.png
wrote spritesheets/resources-images-characterScreen0.png
wrote spritesheets/resources-images-characterScreen1.png
wrote spritesheets/resources-images-countryScreen0.png
wrote spritesheets/resources-images-countryScreen1.png
wrote spritesheets/resources-images-countryScreen2.png
wrote spritesheets/resources-images-statsScreen0.png
wrote spritesheets/resources-images-shopScreen0.png
wrote spritesheets/resources-images-shopScreen-itemdrops_uncomplete0.png
wrote spritesheets/resources-images-shopScreen-shop-assets0.png
wrote spritesheets/resources-images-shopScreen-shop-assets1.png
wrote spritesheets/resources-images-shopScreen-shop-assets2.png
wrote spritesheets/resources-images-shopScreen-shop-assets3.png
wrote spritesheets/resources-images-shopScreen-shop-assets4.png
wrote spritesheets/resources-images-gameScreen0.png
wrote spritesheets/resources-images-gameScreen1.png
wrote spritesheets/resources-images-gameScreen2.png
wrote spritesheets/resources-images-gameScreen3.png
wrote spritesheets/resources-images-gameScreen4.png
wrote spritesheets/resources-images-gameScreen5.png
wrote spritesheets/resources-images-gameScreen6.png
wrote spritesheets/resources-images-gameScreen-backup0.png
wrote spritesheets/resources-images-gameScreen-item_dock0.png
wrote spritesheets/resources-images-gameScreen-items0.png
wrote spritesheets/resources-images-gameScreen-sprite-naruto0.png
wrote spritesheets/resources-images-gameScreen-sprite-stickman0.png
wrote spritesheets/resources-images-gameScreen-sprite-archive-naruto0.png
wrote spritesheets/resources-images-gameScreen-sprite-archive-stickman0.png
wrote spritesheets/resources-images-gameScreen-sprite-base0.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity0.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity1.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity2.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity3.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity4.png
wrote spritesheets/resources-images-topScoreScreen0.png
wrote spritesheets/resources-images-ui0.png
wrote spritesheets/resources-images-titleScreen0.png
wrote resources/images/shopScreen.zip
wrote resources/audio/music/gameScreen.mp3
wrote resources/audio/music/titleScreen.mp3
wrote resources/audio/sounds/jump.mp3
wrote manifest.json
wrote native.js
    [ndk-build]    ndk-build -j 8 DEBUG=1
      [android]    android create project --target android-15 --name calamity_run --path /home/joselito/wt-calamityrun/build/debug/native-android --activity calamity_runActivity --package com.wetalkdirect.studio.calamity_run

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by jwilm** [comment] 2015-02-11 18:08
duplicate of https://github.com/gameclosure/devkit/issues/205. Also, if you're on devkit2, make sure your app name doesn't have underscores or hyphens in it.

**Closed by jwilm** 2015-02-11 18:08 UTC
